name: Build And Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: "https://api.armans.ca"
    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
         switches: -avzr --delete
         path: dist/
         remote_path: /var/www/html
         remote_host: ${{ secrets.HOST }}
         remote_port: ${{ secrets.PORT }}
         remote_user: ${{ secrets.USERNAME }}
         remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

